<robot name="car_sim_move" xmlns:xacro="http://wiki.ros.org/xacro">	
<!--robot name不能与urdf中的一样-->

	<!-- 传动实现:用于连接控制器与关节 -->
	<xacro:macro name="joint_trans" params="joint_name">
		<!-- Transmission is important to link the joints and the controller -->
		<transmission name="${joint_name}_trans">
			<type>
				transmission_interface/SimpleTransmission
			</type>
			<joint name="${joint_name}">
				<hardwareInterface>
					hardware_interface/VelocityJointInterface
				</hardwareInterface>
			</joint>
			<actuator name="${joint_name}_motor">
				<hardwareInterface>
					hardware_interface/VelocityJointInterface
				</hardwareInterface>
				<mechanicalReduction>
					1
				</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro>
	<!-- 每一个驱动轮都需要配置传动装置 -->
	<xacro:joint_trans joint_name="base_l_wheel_joint" />
	<xacro:joint_trans joint_name="base_r_wheel_joint" />

	<!--定义轮间距与轮半径参数-->
	<xacro:property name="wheel_distance" value="0.128" />
	<xacro:property name="wheel_radius" value="0.035" />
	<!-- 控制器 -->
	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<rosDebugLevel>
				Debug
			</rosDebugLevel>
			<publishWheelTF>
				true
			</publishWheelTF>
			<robotNamespace>
				/
			</robotNamespace>
			<publishTf>
				1
			</publishTf>
			<publishWheelJointState>
				true
			</publishWheelJointState>
			<alwaysOn>
				true
			</alwaysOn>
			<updateRate>
				100.0
			</updateRate>
			<legacyMode>
				true
			</legacyMode>
			<leftJoint>
				base_l_wheel_joint
			</leftJoint>
			<!-- 左轮 -->
			<rightJoint>
				base_r_wheel_joint
			</rightJoint>
			<!-- 右轮 -->
			<wheelSeparation>
				${wheel_distance}
			</wheelSeparation>
			<!-- 车轮间距 -->
			<wheelDiameter>
				${wheel_radius*2}
			</wheelDiameter>
			<!-- 车轮直径 -->
			<broadcastTF>
				1
			</broadcastTF>
			<wheelTorque>
				30
			</wheelTorque>
			<wheelAcceleration>
				1.8
			</wheelAcceleration>
			<commandTopic>
				cmd_vel
			</commandTopic>
			<!-- 运动控制话题 -->
			<odometryFrame>
				odom
			</odometryFrame>
			<odometryTopic>
				odom
			</odometryTopic>
			<!-- 里程计话题 -->
			<robotBaseFrame>
				base_link
			</robotBaseFrame>
			<!-- 根坐标系 -->
		</plugin>
	</gazebo>
</robot>
